### ISSUE TITLE
opentelemetry+exporter-trace-otlp-grpc Error

### ISSUE THREAD

**Issue by Dmedina20** [timlrx/contentlayer2#11]
When installing contentlayer with the plugin next-contentlayer I always encounter this error when trying to run my web application: 
![Capture](https://github.com/timlrx/contentlayer2/assets/79009169/888c6471-294a-4cc6-a20c-222db583c879)

Things I have tried: 
-Downgrading to compatible NextJS versions even downgrading to other Contentlayer versions (mostly used 0.3.1)
-Tried installing Contentlayer in a fresh Nextjs project
-Installing the module it says it is having trouble finding, it just acts like it doesn't exist
-Have looked at reddit threads and original Contentlayer issue forums for similar issues and have tried all methods posted (from what I have found) that might fix the issue

What oddly works: 
For some reason when I clone this repo: https://github.com/shadcn-ui/taxonomy that uses Contentlayer for its blogs I run into **no issues**, even building on top of this repository and making other blogs doesn't break anything.

**Comment by timlrx** [comment]
Hi, are you using `contentlayer2` and `next-contentlayer2`? The latest version is `v0.4.5`. Do not use the old contentlayer packages. And just to be certain, try deleting your `node_modules` folder and installing the dependencies again. If that does not work, would it be possible to share the repository or an simplified example repo with the bug? Thanks

**Comment by k-ardliyan** [comment]
Hi, I also experienced a similar error log when installing this package, but it was safe to run in local/prod in the condition that I had completely removed `node_modules` and reinstalled.

This is more or less the error log in the terminal
![error_log_terminal](https://github.com/timlrx/contentlayer2/assets/54210855/5c7de2f3-b5c5-4a4f-aeb0-a21025d144cf)

And this package.json that I installed in my project, does it affect this package too?
![package.json](https://github.com/timlrx/contentlayer2/assets/54210855/12b54f5d-ee5b-477d-a0b8-b0492247859a)

Can the error log be fixed?

**Comment by timlrx** [comment]
@k-ardliyan I have inlined and remove the dependency on `@effect-ts/otel-exporter-trace-otlp-grpc`. Try installing the latest version - `v0.4.6`, there should not be any warning messages.

I don't think it is exactly the same problem as @Dmedina20 though. The peer dependency issue should also throw a warning message but not any module not found error.

**Comment by Dmedina20** [comment]
> Hi, are you using `contentlayer2` and `next-contentlayer2`? The latest version is `v0.4.5`. Do not use the old contentlayer packages. And just to be certain, try deleting your `node_modules` folder and installing the dependencies again. If that does not work, would it be possible to share the repository or an simplified example repo with the bug? Thanks


This worked for me! Thank you!

**Comment by Dmedina20** [comment]
Issue closed

**Comment by 2-fly-4-ai** [comment]
Still get the same issue.

Error: Cannot find package 'C:\Users\Dennis Rounds\Desktop\Github\ravi-nextjs-wireframe\node_modules\.pnpm\@effect-ts+otel-sdk-trace-node@0.15.1_@effect-ts+core@0.60.5_@opentelemetry+api@1.5.0_@opente_7p37urlaiy6r2bt3rmoplftrxu\node_modules\@opentelemetry\sdk-trace-node\package.json' imported from C:\Users\Dennis Rounds\Desktop\Github\ravi-nextjs-wireframe\node_modules\.pnpm\@effect-ts+otel-sdk-trace-node@0.15.1_@effect-ts+core@0.60.5_@opentelemetry+api@1.5.0_@opente_7p37urlaiy6r2bt3rmoplftrxu\node_modules\@effect-ts\otel-sdk-trace-node\_mjs\index.mjs
Did you mean to import "@opentelemetry/sdk-trace-node/build/src/index.js"?
    at legacyMainResolve (node:internal/modules/esm/resolve:215:26)
    at packageResolve (node:internal/modules/esm/resolve:841:14)
    at moduleResolve (node:internal/modules/esm/resolve:927:18)
    at defaultResolve (node:internal/modules/esm/resolve:1157:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:390:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:359:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:234:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:87:39)
    at link (node:internal/modules/esm/module_job:86:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
