### ISSUE TITLE
Support esbuild 0.23

### ISSUE THREAD

**Issue by lishaduck** [timlrx/contentlayer2#23]
If it's just that the package hasn't been updated, then would it be possible to widen the esbuild version to include esbuild 0.23? Thanks!
If it really doesn't support it (possible, that's three majors apart), then feel free to close this issue.

**Comment by lishaduck** [comment]
Speaking of dependencies to update, this is also generating Effect-TS code from 2 years ago, which should probably also get fixed.

**Comment by timlrx** [comment]
Yes, will expend the list of compatible esbuild versions. Updating `Effect-TS` is the toughest part since it cuts across almost the whole package and the syntax of the new functions is also significantly different. I have currently no intention of updating that library.
