### ISSUE TITLE
could not find a copy of esbuild

### ISSUE THREAD

**Issue by hpsoar** [timlrx/contentlayer2#32]
An unexpected error occurred: "could not find a copy of esbuild to link in /Users/roger/app/shadcn-ui/node_modules/@contentlayer2/core/node_modules".

contentlayer2 version 0.5.0

(base) ➜  www git:(main) ✗ esbuild --version
0.23.0

**Comment by timlrx** [comment]
esbuild is a peer dependency and has to be installed separately. If you have already done that, let me know if you are using contentlayer standalone or with next js and if you could include a link to the repo even better. Thanks
