### ISSUE TITLE
Add support for next15 - next-contentlayer2

### ISSUE THREAD

**Issue by alexandprivate** [timlrx/contentlayer2#44]
With the recent release of next15 stable version, a lot of project will migrate to it, currently the peer deps in next-contentlater2 are for:
`"next": "^12 || ^13 || ^14",`

**Comment by k-ardliyan** [comment]
Hi @timlrx,

I fully support this! With the stable release of Next.js 15, having next-contentlayer2 support it would be a huge help. Many projects, including ours, are migrating to Next.js 15, so getting this update soon would be really appreciated.

Hope to see it happen soon! ✨

**Comment by timlrx** [comment]
Yes, most certainly. Let me give it a try tomorrow just to make sure that there are no unforeseen issues and I will bump up the dependencies and publish a new build.

**Comment by alexandprivate** [comment]
Thank you so much @timlrx !

**Comment by timlrx** [comment]
Released as contentlayer and next-contentlayer 0.5.3. You would probably still have to ignore peer-dependencies as many other packages are still not updated but at least contentlayer should not be the issue.
